### ISSUE TITLE
process block handler not on every block, but certain time intervals

### ISSUE THREAD

**Issue by ilinzweilin** [centrifuge/tinlake-subgraph#13]
- start with 1 min & test performance
- on mainnet we need to track 50 loans

**Comment by philipstanislaus** [comment]
Set the time to 5 minutes now (took ~8 seconds for 12 loans before, so it should take ~33 seconds for 50; but we want to be able to redeploy if we find bugs, so we should make sure it should be a factor faster).

CC @denniswell
