### ISSUE TITLE
Delay in tokenBalances() pending supply / redeem amounts after investments execute

### ISSUE THREAD

**Issue by devinblack1337** [centrifuge/tinlake-subgraph#148]
I'm using tokenBalances() to get the pending supply and redeem amounts. Particularly:
`pendingSupplyCurrency`
`pendingRedeemToken`

I've noticed that these amounts can sometimes remain > 0 for a day longer than they should. For example, if a user invests into New Silver, they will have a pendingSupplyCurrency > 0 to represent their pending investment. However, even after the New Silver epoch closes and the investment executes, the graph will return their investment as pending (i.e. pendingSupplyCurrency > 0). This same behavior happens for redemptions as well. I've seen up to a day's delay before the pending amount reverts to 0. 

I imagine this is because of a delay in subgraph syncing or in some other part of our architecture, but I'm unsure

**Comment by denniswell** [comment]
Closed here for now, moved to subgraph backlog
https://centrifuge.hackmd.io/UJUJyF16Q9uQO1zAg44mXA?view
