### ISSUE TITLE
loan list not loading on firefox due to CORS 

### ISSUE THREAD

**Issue by ilinzweilin** [centrifuge/tinlake-subgraph#22]

**Comment by philipstanislaus** [comment]
Got a reply on Discord: https://discordapp.com/channels/438038660412342282/438070183794573313/706607817561473084

**Comment by philipstanislaus** [comment]
This was not fixed it seems. Tried a couple other workarounds without success. Asked in Discord channel whether they can fix it on the server side.

**Comment by philipstanislaus** [comment]
Fixed by The Graph team 🚀
