### ISSUE TITLE
fix shelfRepayaAndler: debt calculation

### ISSUE THREAD

**Issue by ilinzweilin** [centrifuge/tinlake-subgraph#23]
- the graph does not always store the most recent debt, since it's just updated every 20 blocks
- in case a loan is repaid and the stored loan debt & totalDebt are not upToDate, the values might turn negative or string formatted until the next blockupdate. 

Suggestion:
we could just ask the pile for the most recent loan & total debt in the repayment handler

The UI reported the values in the following format:` 0.00000-48500176183`

**Comment by philipstanislaus** [comment]
Directly after repaying a loan, the graph returns the following: 

```
{
  "data": {
    "loans": [
      // snip
      
      {
        "borrowsAggregatedAmount": "1000000000000000000",
        "debt": "-153199186260",
        "id": "0x05597dd9b8e1d4fdb44eb69d20bc3a2feef605e8-0x8",
        "repaysAggregatedAmount": "1000267063495817908"
      }
    ],
    "pools": [
      {
        "id": "0x05597dd9b8e1d4fdb44eb69d20bc3a2feef605e8",
        "totalBorrowsAggregatedAmount": "7000000000000000000",
        "totalBorrowsCount": 6,
        "totalDebt": "-153199186260",
        "totalRepaysAggregatedAmount": "7000393905672757665"
      }
    ]
  }
}
```

**Comment by philipstanislaus** [comment]
There are 2 issues here: 

1. `baseToDisplay('-0', 2)` outputs `-0.-0`
2. Subgraph should maximally subtract the current value when repaying, not more.
